# Generated by Django 3.2.6 on 2021-08-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0002_alter_auction_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='post',
            new_name='autionpost',
        ),
    ]
