# Generated by Django 3.2.5 on 2021-11-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar_user/%Y/%m'),
        ),
    ]
