# Generated by Django 3.2.6 on 2021-08-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0003_rename_post_auction_autionpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
