# Generated by Django 3.2.5 on 2021-11-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0004_auto_20211121_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='money_auctioned',
            field=models.IntegerField(default=0),
        ),
    ]
