# Generated by Django 3.2.5 on 2021-12-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0006_auto_20211206_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id']},
        ),
    ]
