# Generated by Django 3.2.5 on 2021-12-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0007_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='auction',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='report',
            name='object_report',
            field=models.PositiveSmallIntegerField(choices=[(1, 'USER'), (2, 'POST'), (3, 'COMMENT')], default=1),
        ),
    ]
