# Generated by Django 3.2.5 on 2021-12-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0008_report_object_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionpost',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='auctionpost',
            name='end_date',
            field=models.DateField(default=None),
        ),
    ]
