# Generated by Django 3.2.5 on 2021-12-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0008_auto_20211225_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionpost',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='auction',
            name='end_date',
        ),
        migrations.AddField(
            model_name='auctionpost',
            name='end_date',
            field=models.DateField(default=None),
        ),
    ]
