# Generated by Django 3.2.5 on 2021-12-28 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0010_report_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user_report',
        ),
        migrations.AddField(
            model_name='report',
            name='user_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to=settings.AUTH_USER_MODEL),
        ),
    ]
