# Generated by Django 3.2.5 on 2021-12-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0011_auto_20211228_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='object_report',
            new_name='object',
        ),
    ]
