# Generated by Django 3.2.5 on 2021-12-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0012_rename_object_report_report_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='object',
            new_name='object_report',
        ),
    ]
